### ISSUE TITLE
vulnerability container scanning also for ubuntu container

### ISSUE THREAD

**Issue by Echsecutor** [IDunion/indy-node-container#14]
currently we only scan `latest`

**Comment by Echsecutor** [comment]
we have to take care not to clutter https://github.com/IDunion/indy-node-container/security/code-scanning completely

**Comment by mgmgwi** [comment]
This has been addressed in #17 

Action: https://github.com/IDunion/indy-node-container/actions/workflows/trivy-ubuntu.yml
Report: https://github.com/IDunion/indy-node-container/security/code-scanning?query=tool%3ATrivyUbuntu18Latest

So I think this can be closed.
