### ISSUE TITLE
push latest images only on release

### ISSUE THREAD

**Issue by Echsecutor** [IDunion/indy-node-container#15]
the current build action builds and pushes images with buster/ubuntu/latest tags to the github container registry for every git push.  The build & push action should be restricted to master. building images for PRs would be enough. 

Possible solution: split actions

**Comment by mgmgwi** [comment]
In #18 I modified the action trigger to

https://github.com/IDunion/indy-node-container/blob/c05cc8bad2e7874aa6bd4aded367c028c589359b/.github/workflows/build-buster.yml#L3-L9

This would build and push on PRs but with the branch name as tag. The `latest` tag will be build and pushed on release or `git push tags` command.

Is this sufficient or do we need/want to build on branches without PRs?

**Comment by Echsecutor** [comment]
already fixed
