### ISSUE TITLE
not creating new batch because there are already 4 in flight out of 4 allowed

### ISSUE THREAD

**Issue by trustcerts** [IDunion/indy-node-container#16]
Indy decided to limit the number to 4, see https://jira.hyperledger.org/browse/INDY-1863

Main reason to limit it was because of performance: A high number can lead for nodes to get out of order and falling out of consensus.

## Reason:
All in all its a consensus problem because of the design decisions.
Position of the error:
https://github.com/hyperledger/indy-plenum/blob/f812a72197bc0740d4c6b75b796beff8f88c73f9/plenum/server/consensus/ordering_service.py

https://github.com/hyperledger/indy-plenum/blob/f812a72197bc0740d4c6b75b796beff8f88c73f9/plenum/test/replica/test_max_3pc_batches_in_flight.py

## Todo:
Fixing consensus seems to be a heavy tasks. Changing the number in https://github.com/hyperledger/indy-plenum/blob/f812a72197bc0740d4c6b75b796beff8f88c73f9/plenum/config.py for test purpose should require a rebuild.

To specify if it is a critical bug, the nodes that are throwing the message have to validate how often it is thrown to evaluate if it can be categorized as a warning or a critical error.

**Comment by Echsecutor** [comment]
@trustcerts Thanks for the issue! That is certainly a relevant issue, but not really related to building container images for indy node, is it? Did you accidentally open this issue in the wrong repo? ;) Given that you already found the right file to (quick) fix this, the issue might be better off in https://github.com/hyperledger/indy-plenum ? You could also ask at e.g. https://chat.hyperledger.org/channel/indy-node / https://chat.hyperledger.org/channel/indy-contributors for the best place

**Comment by trustcerts** [comment]
@Echsecutor we had this issue in one of the meetings so I thought placing it here helps everyone to track it. Since only some of our nodes are throwing this error we should collect more information about them to find a pattern before we can submit an issue in the official repos.

**Comment by Echsecutor** [comment]
@trustcerts maybe we should open an Issue tracker /seperate github repo for AP6/the test network? For now I would recommend moving it to https://nextcloud.idunion.org/apps/deck/#/board/19 + reporting upstream
