### ISSUE TITLE
Change tagging schema

### ISSUE THREAD

**Issue by mgmgwi** [IDunion/indy-node-container#22]
I would like to propose a modification to the tagging schema. At the moment tags are created like this:

**Old:**
`indy_node`:`[latest | ubuntu | buster | version ]`

So there is no distinction between the base image OS distribution in correlation to the version number. I would like to change it like this:

**New:**
`indy_node`:`[version]`-`distro` - with `distro=( buster | ubuntu )`

e.g.
- `indy_node:latest` ( --> buster)
- `indy_node:buster` (latest buster)
- `indy_node:v0.1.2-buster`
- `indy_node:ubuntu` (latest ubuntu)
- `indy_node:v0.1.2-ubuntu`

Update 2021-06-21: remove `latest` tag for ubuntu (see meeting notes [2021-06-18](https://github.com/mgmgwi/indy-node-container/blob/9cbbfa79463988e8a12550d9f0db2e8d2e2021df/minutes/2021-06-18.md) ). The `latest` tag should always point to `buster`.

**Comment by Echsecutor** [comment]
mostly fixed. open: `latest` tag is currently still assigned to the latest finished build
