### ISSUE TITLE
Fix consensus

### ISSUE THREAD

**Issue by Echsecutor** [IDunion/indy-node-container#38]
In https://github.com/IDunion/indy-node-container/issues/10 it turns out that our ubuntu 18/debian images have consensus problems with the existing ubuntu 16 Version.

We need to compare e.g.
- https://github.com/Echsecutor/docker-indy-node/blob/master/node/Dockerfile
- https://github.com/IDunion/indy-node-container/blob/main/build/Dockerfile.ubuntu18

and fix our ubuntu 18 / debian images!

**Comment by Echsecutor** [comment]
Should we wait for the ubunu 20 debs?

**Comment by udosson** [comment]
I suggest publishing an indy-node image based on Ubuntu 16.04 even though Ubuntu 16.04 is deprecated. Let's use our resources to support the Hyperledger Indy community in publishing the first release of Debian files of Indy-Node for Ubuntu 20.04.
These issues provide a good starting point: https://github.com/hyperledger/indy-plenum/labels/Ubuntu%2020.04

**Comment by Echsecutor** [comment]
- Issue with ubuntu 18 fixed in https://github.com/IDunion/indy-node-container/pull/66
- Debian Images 2do
- Ubuntu 20 image will be build only for 1.13 -> with new libsodium
