### ISSUE TITLE
Setting file/folder permissions on startup

### ISSUE THREAD

**Issue by Echsecutor** [IDunion/indy-node-container#41]
```
PermissionError: [Errno 13] Permission denied: '/var/lib/indy/idunion_local_test/data'
```

-> https://github.com/IDunion/indy-node-container/blob/main/build/init_and_run.sh#L46

**Comment by mgmgwi** [comment]
Should we fix this in the script or should/must the user take care of the correct permission outside of the container?

**Comment by Echsecutor** [comment]
@tsurai you had this issue, right? Could you check if the recent merge of https://github.com/IDunion/indy-node-container/pull/55 fixes it?

**Comment by tsurai** [comment]
Yes, this seems to do the trick
