### ISSUE TITLE
Analyze Vulnerability Scan

### ISSUE THREAD

**Issue by Echsecutor** [IDunion/indy-node-container#5]
@udosson has provided a vulnerability scan of our docker container:
https://github.com/IDunion/indy-node-container/blob/main/minutes/clair-report-indy-node-slim-buster.json

We should at least check the 8 critical/high severity issues

**Comment by solidnerd** [comment]
Hey,
we could use [trivy](https://github.com/aquasecurity/trivy) for Continous Scanning and compare it.

**Comment by mgmgwi** [comment]
fyi: https://github.com/IDunion/indy-node-container/security/code-scanning?query=ref%3Arefs%2Fpull%2F12%2Fmerge

**Comment by Echsecutor** [comment]
current scan results: https://github.com/IDunion/indy-node-container/security/code-scanning

**Comment by mgmgwi** [comment]
IMO this can be closed. Running trivy with `--unfixed` results in 0 CVEs. See also #21
